# mapping of english letters to their russian counterparts
russian_conversion_map = {
    "a" : "а",
    "b" : "б",
    "c" : "ц",
    "d" : "д",
    "e" : "е",
    "eo" : "ё",
    "f" : "ф",
    "g" : "г",
    "h" : "х",
    "i" : "и",
    "ie": "й",
    "zj" : "ж",
    "k" : "к",
    "l" : "л",
    "m" : "м",
    "n" : "н",
    "o" : "о",
    "p" : "п",
    "q" : "",
    "r" : "р",
    "s" : "с",
    "t" : "т",
    "u" : "у",
    "v" : "в",
    "w" : "",
    "x" : "",
    "ya" : "я",
    "ja": "я",
    "z" : "з",
    "ch": "ч",
    "sh": "ш",
    "sch": "щ",
}

# the maximum value of how many english characters go to one russian letter
max_layer = 3